In [0]:
import pandas as pd
from pandas.tseries.offsets import MonthEnd

In [0]:
# !pip  install xlrd

In [0]:
df = pd.read_excel("/Volumes/myfirst/default/zimra/CPI_USD_May- 24_email.xls",header=1)
df

   Unnamed: 0  ...                         Unnamed: 16
0         NaN  ...  Inflation Rate         (%)  Annual
1     Weights  ...                                 NaN
2         NaN  ...                                 NaN
3         NaN  ...                                 NaN
4        2019  ...                                 NaN
..        ...  ...                                 ...
64       2024  ...                           -2.884582
65        NaN  ...                            1.587943
66        NaN  ...                            2.225046
67        NaN  ...                            3.197342
68        NaN  ...                            3.483983

[69 rows x 17 columns]

change the column names

In [0]:
df.columns = ["Year","Month"] + df.iloc[0,2:].values.tolist()
df = df.drop(index=0)
df

       Year  ... Inflation Rate         (%)  Annual
1   Weights  ...                                NaN
2       NaN  ...                                NaN
3       NaN  ...                                NaN
4      2019  ...                                NaN
5       NaN  ...                                NaN
..      ...  ...                                ...
64     2024  ...                          -2.884582
65      NaN  ...                           1.587943
66      NaN  ...                           2.225046
67      NaN  ...                           3.197342
68      NaN  ...                           3.483983

[68 rows x 17 columns]

drop rows with all null values and the weights row

In [0]:
df = df.dropna(how="all").reset_index(drop=True)
df = df.drop(index=0)
df

    Year Month  ... Inflation Rate (%) Monthly    Inflation Rate         (%)  Annual
1   2019   Jun  ...                           NaN                                NaN
2    NaN   Jul  ...                     -0.761859                                NaN
3    NaN   Aug  ...                     -1.509782                                NaN
4    NaN   Sep  ...                     -15.36114                                NaN
5    NaN   Oct  ...                     17.533382                                NaN
6    NaN   Nov  ...                     -2.333053                                NaN
7    NaN   Dec  ...                      2.102968                                NaN
8   2020   Jan  ...                      -0.85939                                NaN
9    NaN   Feb  ...                     -9.335626                                NaN
10   NaN   Mar  ...                     -1.959227                                NaN
11   NaN   Apr  ...                     -1.498205                                NaN
12   NaN   May  ...                     -0.208095                                NaN
13   NaN   Jun  ...                     -0.513267                         -16.441941
14   NaN   Jul  ...                      0.158883                          -15.66668
15   NaN   Aug  ...                     -1.031773                          -15.25738
16   NaN   Sep  ...                     -1.303952                          -1.182959
17   NaN   Oct  ...                     -0.164747                         -16.062789
18   NaN   Nov  ...                      1.828584                         -12.486182
19   NaN   Dec  ...                      2.673026                         -11.997578
20  2021   Jan  ...                      1.609709                          -9.805876
21   NaN   Feb  ...                      -0.06402                          -0.582358
22   NaN   Mar  ...                       0.59759                           2.010365
23   NaN   Apr  ...                      0.241976                           3.812531
24   NaN   May  ...                      1.858589                           5.962482
25   NaN   Jun  ...                      4.159816                          10.939743
26   NaN   Jul  ...                      0.006205                          10.770632
27   NaN   Aug  ...                      0.531533                          12.520369
28   NaN   Sep  ...                       1.02944                          15.180599
29   NaN   Oct  ...                        1.5179                           17.12188
30   NaN   Nov  ...                      1.079588                          16.260394
31   NaN   Dec  ...                      0.798333                          14.137612
32  2022   Jan  ...                      1.449548                          13.957704
33   NaN   Feb  ...                      1.568895                          15.819728
34   NaN   Mar  ...                      1.592925                          16.965676
35   NaN   Apr  ...                       5.47226                          23.068545
36   NaN   May  ...                      3.004931                          24.453589
37   NaN   Jun  ...                      8.735938                           29.92129
38   NaN   Jul  ...                      3.698319                          34.717834
39   NaN   Aug  ...                      1.590686                          36.137157
40   NaN   Sep  ...                     -0.737536                          33.756157
41   NaN   Oct  ...                      2.993262                          35.700038
42   NaN   Nov  ...                      1.162112                          35.810827
43   NaN   Dec  ...                      0.542199                          35.465725
44  2023   Jan  ...                      -0.37904                          33.024009
45   NaN   Feb  ...                     -4.577808                          24.973718
46   NaN   Mar  ...                      -0.45736                          22.451576
47   NaN   Apr  ...                      -0.19689                          15.869785
48   NaN   May  ...                      -0.18863                          12.277363
49   NaN   Jun  ...                      -0.55442                           2.684427
50   NaN   Jul  ...                       0.11637                          -0.862501
51   NaN   Aug  ...                      0.003678                          -2.411186
52   NaN   Sep  ...                      0.245532                          -1.444693
53   NaN   Oct  ...                      0.811727                          -3.532225
54   NaN   Nov  ...                      0.855593                          -3.824521
55   NaN   Dec  ...                      1.413229                          -2.991321
56  2024   Jan  ...                     -0.269426                          -2.884582
57   NaN   Feb  ...                     -0.183263                           1.587943
58   NaN   Mar  ...                      0.166916                           2.225046
59   NaN   Apr  ...                       0.75237                           3.197342
60   NaN   May  ...                      0.088607                           3.483983

[60 rows x 17 columns]

fill null values in _year_  column by previous non null value

In [0]:
df[["Year"]] = df[["Year"]].ffill()
df

/home/spark-f4142abc-8567-4fc9-b00e-de/.ipykernel/14510/command-8170175846243618-1606669893:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[["Year"]] = df[["Year"]].ffill()

    Year Month  ... Inflation Rate (%) Monthly    Inflation Rate         (%)  Annual
1   2019   Jun  ...                           NaN                                NaN
2   2019   Jul  ...                     -0.761859                                NaN
3   2019   Aug  ...                     -1.509782                                NaN
4   2019   Sep  ...                     -15.36114                                NaN
5   2019   Oct  ...                     17.533382                                NaN
6   2019   Nov  ...                     -2.333053                                NaN
7   2019   Dec  ...                      2.102968                                NaN
8   2020   Jan  ...                      -0.85939                                NaN
9   2020   Feb  ...                     -9.335626                                NaN
10  2020   Mar  ...                     -1.959227                                NaN
11  2020   Apr  ...                     -1.498205                                NaN
12  2020   May  ...                     -0.208095                                NaN
13  2020   Jun  ...                     -0.513267                         -16.441941
14  2020   Jul  ...                      0.158883                          -15.66668
15  2020   Aug  ...                     -1.031773                          -15.25738
16  2020   Sep  ...                     -1.303952                          -1.182959
17  2020   Oct  ...                     -0.164747                         -16.062789
18  2020   Nov  ...                      1.828584                         -12.486182
19  2020   Dec  ...                      2.673026                         -11.997578
20  2021   Jan  ...                      1.609709                          -9.805876
21  2021   Feb  ...                      -0.06402                          -0.582358
22  2021   Mar  ...                       0.59759                           2.010365
23  2021   Apr  ...                      0.241976                           3.812531
24  2021   May  ...                      1.858589                           5.962482
25  2021   Jun  ...                      4.159816                          10.939743
26  2021   Jul  ...                      0.006205                          10.770632
27  2021   Aug  ...                      0.531533                          12.520369
28  2021   Sep  ...                       1.02944                          15.180599
29  2021   Oct  ...                        1.5179                           17.12188
30  2021   Nov  ...                      1.079588                          16.260394
31  2021   Dec  ...                      0.798333                          14.137612
32  2022   Jan  ...                      1.449548                          13.957704
33  2022   Feb  ...                      1.568895                          15.819728
34  2022   Mar  ...                      1.592925                          16.965676
35  2022   Apr  ...                       5.47226                          23.068545
36  2022   May  ...                      3.004931                          24.453589
37  2022   Jun  ...                      8.735938                           29.92129
38  2022   Jul  ...                      3.698319                          34.717834
39  2022   Aug  ...                      1.590686                          36.137157
40  2022   Sep  ...                     -0.737536                          33.756157
41  2022   Oct  ...                      2.993262                          35.700038
42  2022   Nov  ...                      1.162112                          35.810827
43  2022   Dec  ...                      0.542199                          35.465725
44  2023   Jan  ...                      -0.37904                          33.024009
45  2023   Feb  ...                     -4.577808                          24.973718
46  2023   Mar  ...                      -0.45736                          22.451576
47  2023   Apr  ...                      -0.19689                          15.869785
48  2023   May  ...                      -0.18863                          12.277363
49  2023   Jun  ...                      -0.55442                           2.684427
50  2023   Jul  ...                       0.11637                          -0.862501
51  2023   Aug  ...                      0.003678                          -2.411186
52  2023   Sep  ...                      0.245532                          -1.444693
53  2023   Oct  ...                      0.811727                          -3.532225
54  2023   Nov  ...                      0.855593                          -3.824521
55  2023   Dec  ...                      1.413229                          -2.991321
56  2024   Jan  ...                     -0.269426                          -2.884582
57  2024   Feb  ...                     -0.183263                           1.587943
58  2024   Mar  ...                      0.166916                           2.225046
59  2024   Apr  ...                       0.75237                           3.197342
60  2024   May  ...                      0.088607                           3.483983

[60 rows x 17 columns]

In [0]:
df["date"] = pd.to_datetime(df["Year"].astype(str)+"-"+df["Month"],format="%Y-%b") + MonthEnd(0)
df = df.drop(columns=["Year","Month"])
df

   Food and non alcoholic beverages  ...       date
1                         67.544178  ... 2019-06-30
2                         68.167793  ... 2019-07-31
3                         70.624078  ... 2019-08-31
4                          55.88564  ... 2019-09-30
5                         77.085842  ... 2019-10-31
6                         76.609203  ... 2019-11-30
7                         81.049189  ... 2019-12-31
8                         81.077289  ... 2020-01-31
9                         72.135673  ... 2020-02-29
10                        65.984352  ... 2020-03-31
11                        70.424403  ... 2020-04-30
12                        68.533071  ... 2020-05-31
13                        61.280136  ... 2020-06-30
14                        65.059635  ... 2020-07-31
15                        62.585897  ... 2020-08-31
16                        62.017296  ... 2020-09-30
17                        61.929223  ... 2020-10-31
18                        64.130651  ... 2020-11-30
19                        66.234119  ... 2020-12-31
20                        67.338097  ... 2021-01-31
21                        68.307217  ... 2021-02-28
22                        68.329656  ... 2021-03-31
23                        68.263654  ... 2021-04-30
24                        68.340124  ... 2021-05-31
25                        69.815066  ... 2021-06-30
26                        69.433982  ... 2021-07-31
27                        69.534272  ... 2021-08-31
28                        70.699315  ... 2021-09-30
29                        72.479614  ... 2021-10-31
30                        74.204038  ... 2021-11-30
31                        74.913741  ... 2021-12-31
32                        76.029832  ... 2022-01-31
33                        77.752438  ... 2022-02-28
34                        79.551398  ... 2022-03-31
35                        82.922648  ... 2022-04-30
36                        87.735452  ... 2022-05-31
37                              100  ... 2022-06-30
38                       108.200056  ... 2022-07-31
39                       111.161221  ... 2022-08-31
40                       106.225494  ... 2022-09-30
41                       108.205852  ... 2022-10-31
42                         108.2623  ... 2022-11-30
43                       109.683378  ... 2022-12-31
44                       108.392115  ... 2023-01-31
45                       102.280021  ... 2023-02-28
46                       101.242302  ... 2023-03-31
47                       100.931953  ... 2023-04-30
48                       100.592371  ... 2023-05-31
49                       100.454335  ... 2023-06-30
50                       100.280064  ... 2023-07-31
51                       100.248502  ... 2023-08-31
52                       100.594336  ... 2023-09-30
53                       101.652409  ... 2023-10-31
54                       102.008356  ... 2023-11-30
55                       104.309802  ... 2023-12-31
56                       105.679688  ... 2024-01-31
57                       104.912639  ... 2024-02-29
58                       105.058275  ... 2024-03-31
59                       104.747112  ... 2024-04-30
60                       104.881273  ... 2024-05-31

[60 rows x 16 columns]

Replacing null values in the inflation rate with 0, missing because of lag not available

In [0]:
df[df.columns[-3:-1].tolist()] = df[df.columns[-3:-1].tolist()].fillna(0)
df

/home/spark-f4142abc-8567-4fc9-b00e-de/.ipykernel/14510/command-5105454624732106-2047059431:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[df.columns[-3:-1].tolist()] = df[df.columns[-3:-1].tolist()].fillna(0)

   Food and non alcoholic beverages  ...       date
1                         67.544178  ... 2019-06-30
2                         68.167793  ... 2019-07-31
3                         70.624078  ... 2019-08-31
4                          55.88564  ... 2019-09-30
5                         77.085842  ... 2019-10-31
6                         76.609203  ... 2019-11-30
7                         81.049189  ... 2019-12-31
8                         81.077289  ... 2020-01-31
9                         72.135673  ... 2020-02-29
10                        65.984352  ... 2020-03-31
11                        70.424403  ... 2020-04-30
12                        68.533071  ... 2020-05-31
13                        61.280136  ... 2020-06-30
14                        65.059635  ... 2020-07-31
15                        62.585897  ... 2020-08-31
16                        62.017296  ... 2020-09-30
17                        61.929223  ... 2020-10-31
18                        64.130651  ... 2020-11-30
19                        66.234119  ... 2020-12-31
20                        67.338097  ... 2021-01-31
21                        68.307217  ... 2021-02-28
22                        68.329656  ... 2021-03-31
23                        68.263654  ... 2021-04-30
24                        68.340124  ... 2021-05-31
25                        69.815066  ... 2021-06-30
26                        69.433982  ... 2021-07-31
27                        69.534272  ... 2021-08-31
28                        70.699315  ... 2021-09-30
29                        72.479614  ... 2021-10-31
30                        74.204038  ... 2021-11-30
31                        74.913741  ... 2021-12-31
32                        76.029832  ... 2022-01-31
33                        77.752438  ... 2022-02-28
34                        79.551398  ... 2022-03-31
35                        82.922648  ... 2022-04-30
36                        87.735452  ... 2022-05-31
37                              100  ... 2022-06-30
38                       108.200056  ... 2022-07-31
39                       111.161221  ... 2022-08-31
40                       106.225494  ... 2022-09-30
41                       108.205852  ... 2022-10-31
42                         108.2623  ... 2022-11-30
43                       109.683378  ... 2022-12-31
44                       108.392115  ... 2023-01-31
45                       102.280021  ... 2023-02-28
46                       101.242302  ... 2023-03-31
47                       100.931953  ... 2023-04-30
48                       100.592371  ... 2023-05-31
49                       100.454335  ... 2023-06-30
50                       100.280064  ... 2023-07-31
51                       100.248502  ... 2023-08-31
52                       100.594336  ... 2023-09-30
53                       101.652409  ... 2023-10-31
54                       102.008356  ... 2023-11-30
55                       104.309802  ... 2023-12-31
56                       105.679688  ... 2024-01-31
57                       104.912639  ... 2024-02-29
58                       105.058275  ... 2024-03-31
59                       104.747112  ... 2024-04-30
60                       104.881273  ... 2024-05-31

[60 rows x 16 columns]

Check if there are still null values

In [0]:
df.isna().sum()

Food and non alcoholic beverages                  0
Alcoholic beverages and tobacco                   0
Clothing and footwear                             0
Housing water electricity gas and other fuels     0
Furniture, household equipment and maintenance    0
Health                                            0
Transport                                         0
Communication                                     0
Recreation and culture                            0
Education                                         0
Restaurants and hotels                            0
Miscellaneous goods and services                  0
All Items                                         0
Inflation Rate (%) Monthly                        0
Inflation Rate         (%)  Annual                0
date                                              0
dtype: int64

In [0]:
df.to_csv("/Volumes/myfirst/default/zimra/zimra-cunsumer-price-index-2019-2024.csv",index=False)
df = pd.read_csv("/Volumes/myfirst/default/zimra/zimra-cunsumer-price-index-2019-2024.csv")
df

    Food and non alcoholic beverages  ...        date
0                          67.544178  ...  2019-06-30
1                          68.167793  ...  2019-07-31
2                          70.624078  ...  2019-08-31
3                          55.885640  ...  2019-09-30
4                          77.085842  ...  2019-10-31
5                          76.609203  ...  2019-11-30
6                          81.049189  ...  2019-12-31
7                          81.077289  ...  2020-01-31
8                          72.135673  ...  2020-02-29
9                          65.984352  ...  2020-03-31
10                         70.424403  ...  2020-04-30
11                         68.533071  ...  2020-05-31
12                         61.280136  ...  2020-06-30
13                         65.059635  ...  2020-07-31
14                         62.585897  ...  2020-08-31
15                         62.017296  ...  2020-09-30
16                         61.929223  ...  2020-10-31
17                         64.130651  ...  2020-11-30
18                         66.234119  ...  2020-12-31
19                         67.338097  ...  2021-01-31
20                         68.307217  ...  2021-02-28
21                         68.329656  ...  2021-03-31
22                         68.263654  ...  2021-04-30
23                         68.340124  ...  2021-05-31
24                         69.815066  ...  2021-06-30
25                         69.433982  ...  2021-07-31
26                         69.534272  ...  2021-08-31
27                         70.699315  ...  2021-09-30
28                         72.479614  ...  2021-10-31
29                         74.204038  ...  2021-11-30
30                         74.913741  ...  2021-12-31
31                         76.029832  ...  2022-01-31
32                         77.752438  ...  2022-02-28
33                         79.551398  ...  2022-03-31
34                         82.922648  ...  2022-04-30
35                         87.735452  ...  2022-05-31
36                        100.000000  ...  2022-06-30
37                        108.200056  ...  2022-07-31
38                        111.161221  ...  2022-08-31
39                        106.225494  ...  2022-09-30
40                        108.205852  ...  2022-10-31
41                        108.262300  ...  2022-11-30
42                        109.683378  ...  2022-12-31
43                        108.392115  ...  2023-01-31
44                        102.280021  ...  2023-02-28
45                        101.242302  ...  2023-03-31
46                        100.931953  ...  2023-04-30
47                        100.592371  ...  2023-05-31
48                        100.454335  ...  2023-06-30
49                        100.280064  ...  2023-07-31
50                        100.248502  ...  2023-08-31
51                        100.594336  ...  2023-09-30
52                        101.652409  ...  2023-10-31
53                        102.008356  ...  2023-11-30
54                        104.309802  ...  2023-12-31
55                        105.679688  ...  2024-01-31
56                        104.912639  ...  2024-02-29
57                        105.058275  ...  2024-03-31
58                        104.747112  ...  2024-04-30
59                        104.881273  ...  2024-05-31

[60 rows x 16 columns]